apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: f7d8bvfyu-nodejs
  janus-idp.io/tekton: f7d8bvfyu-nodejs
  backstage.io/kubernetes-id: f7d8bvfyu-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: f7d8bvfyu-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
